import type { Metadata } from "next";
import { ProsePage } from "@/components/marketing/MarketingShell";

export const metadata: Metadata = { title: "Terms of Service", description: "AlgoBook Terms of Service — rules and guidelines for using the platform." };

export default function TermsPage() {
  return (
    <ProsePage title="Terms of Service" updated="September 8, 2026" intro="Welcome to AlgoBook. By accessing or using our platform at algobook.ai you agree to be bound by these Terms of Service. AlgoBook is operated by CognitiveSquad.">
      <section><h2>1. Acceptance of terms</h2><p>By creating an account or using AlgoBook, you confirm that you are at least 13 years old and agree to comply with these Terms. If you do not agree, please do not use our services.</p></section>
      <section>
        <h2>2. Account registration</h2>
        <ul>
          <li>You must sign in using a valid Google account.</li>
          <li>You are responsible for maintaining the security of your account.</li>
          <li>You must provide accurate information and keep your profile up to date.</li>
          <li>One person may not maintain more than one account.</li>
        </ul>
      </section>
      <section>
        <h2>3. Subscription &amp; payments</h2>
        <h3>3.1 Free tier</h3>
        <p>The free tier includes a limited number of AI-generated problems per day, unlimited problems from the shared verified pool, a daily run allowance, hints up to level 2, the daily challenge and the leaderboard. Exact limits are shown on the pricing page and in Settings.</p>
        <h3>3.2 Pro plan</h3>
        <ul>
          <li><strong>Monthly plan:</strong> ₹499 per 30 days</li>
          <li><strong>Yearly plan:</strong> ₹4,999 per 365 days (save 17 %)</li>
        </ul>
        <p>Pro includes a much higher daily generation allowance, level-3 contextual hints, editorials, the AI tutor, inline code completion, post-solve code review and mock interviews.</p>
        <h3>3.3 No auto-renewal</h3>
        <p>AlgoBook subscriptions do not auto-renew. When your subscription period ends you can manually renew if you wish to continue using Pro features. There are no automatic charges.</p>
        <h3>3.4 Refund policy</h3>
        <p>Since there is no auto-renewal, refunds are not typically provided. If you experience a technical issue that prevents you from using the service, contact us within 7 days of purchase at <a href="mailto:contact@cognitivesquad.com">contact@cognitivesquad.com</a>.</p>
      </section>
      <section>
        <h2>4. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use AlgoBook for any unlawful purpose</li>
          <li>Attempt to gain unauthorised access to any part of the platform</li>
          <li>Submit malicious code intended to harm our infrastructure or the execution sandbox</li>
          <li>Share your account with others</li>
          <li>Scrape, crawl or use automated tools to extract data from AlgoBook</li>
          <li>Reproduce, redistribute or sell content generated by AlgoBook</li>
          <li>Use the platform to harass, abuse or harm other users</li>
        </ul>
      </section>
      <section>
        <h2>5. Intellectual property</h2>
        <h3>5.1 Our content</h3>
        <p>The AlgoBook platform, including its design, features and AI-generated problems, editorials and hints, is the intellectual property of CognitiveSquad. You may not copy, modify or distribute our platform content.</p>
        <h3>5.2 Your content</h3>
        <p>You retain ownership of the code you write on AlgoBook. By using the platform you grant us a limited licence to store and process your submissions to provide the service, including sending them to our AI and code-execution providers.</p>
      </section>
      <section><h2>6. AI-generated content</h2><p>Problems, hints, editorials, reviews and tutor replies are generated by AI models and verified by automated execution where possible. While we strive for accuracy, AI-generated content may occasionally contain errors. AlgoBook is a practice tool and should not be the sole basis for interview-preparation decisions. You can flag a problem from the workspace; problems flagged by multiple users are retired.</p></section>
      <section><h2>7. Code execution</h2><p>Code submitted through AlgoBook is executed in a sandboxed environment. We reserve the right to limit execution time, memory usage and the number of executions to prevent abuse.</p></section>
      <section><h2>8. Termination</h2><p>We reserve the right to suspend or terminate your account if you violate these Terms. You may delete your account at any time from Settings → Danger zone.</p></section>
      <section><h2>9. Limitation of liability</h2><p>AlgoBook is provided &ldquo;as is&rdquo; without warranties of any kind. We are not liable for any indirect, incidental or consequential damages arising from your use of the platform. Our total liability shall not exceed the amount you paid for the service in the 12 months preceding the claim.</p></section>
      <section><h2>10. Changes to terms</h2><p>We may update these Terms from time to time. Continued use of AlgoBook after changes constitutes acceptance of the new Terms. We will make reasonable efforts to notify users of significant changes.</p></section>
      <section><h2>11. Governing law</h2><p>These Terms are governed by the laws of India. Any disputes shall be resolved in the courts of competent jurisdiction in India.</p></section>
      <section><h2>12. Contact us</h2><p>For questions about these Terms, email <a href="mailto:contact@cognitivesquad.com">contact@cognitivesquad.com</a>.</p></section>
    </ProsePage>
  );
}
