import type { Metadata } from "next";
import Link from "next/link";
import { Code2, ArrowLeft } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "AlgoBook Terms of Service — rules and guidelines for using our platform.",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border/50 bg-background/80 backdrop-blur-xl sticky top-0 z-40">
        <div className="mx-auto max-w-4xl flex items-center justify-between px-6 py-3">
          <Link href="/" className="flex items-center gap-2">
            <div className="h-8 w-8 rounded-lg bg-primary flex items-center justify-center">
              <Code2 className="h-5 w-5 text-primary-foreground" />
            </div>
            <span className="text-lg font-bold tracking-tight">AlgoBook</span>
          </Link>
          <Link href="/dashboard" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="h-3.5 w-3.5" /> Back
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-4xl px-6 py-16">
        <h1 className="text-4xl font-bold tracking-tight mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: March 25, 2026</p>

        <div className="prose prose-invert prose-sm max-w-none space-y-8 text-muted-foreground [&_h2]:text-foreground [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:mt-10 [&_h2]:mb-4 [&_h3]:text-foreground [&_h3]:text-base [&_h3]:font-medium [&_h3]:mt-6 [&_h3]:mb-2 [&_strong]:text-foreground [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:space-y-1 [&_ol]:list-decimal [&_ol]:pl-6 [&_ol]:space-y-1">
          <p className="text-base text-foreground/80 leading-relaxed">
            Welcome to AlgoBook. By accessing or using our platform at algobook.ai, you agree to be bound by these Terms of Service. AlgoBook is operated by CognitiveSquad.
          </p>

          <h2>1. Acceptance of Terms</h2>
          <p>By creating an account or using AlgoBook, you confirm that you are at least 13 years old and agree to comply with these Terms. If you do not agree, please do not use our services.</p>

          <h2>2. Account Registration</h2>
          <ul>
            <li>You must sign in using a valid Google account.</li>
            <li>You are responsible for maintaining the security of your account.</li>
            <li>You must provide accurate information and keep your profile up to date.</li>
            <li>One person may not maintain more than one account.</li>
          </ul>

          <h2>3. Subscription &amp; Payments</h2>
          <h3>3.1 Free Tier</h3>
          <p>AlgoBook offers a free tier with limited functionality including dashboard access, browsing existing projects, and viewing submission history.</p>

          <h3>3.2 Pro Plan</h3>
          <ul>
            <li><strong>Monthly Plan:</strong> ₹499/month</li>
            <li><strong>Yearly Plan:</strong> ₹4,999/year (Save 17%)</li>
          </ul>
          <p>Pro plans include unlimited AI question generation, code execution, smart hints, unlimited projects, and performance tracking.</p>

          <h3>3.3 No Auto-Renewal</h3>
          <p>AlgoBook subscriptions do <strong>not</strong> auto-renew. When your subscription period ends, you can manually renew if you wish to continue using Pro features. There are no automatic charges.</p>

          <h3>3.4 Refund Policy</h3>
          <p>Since there is no auto-renewal, refunds are not typically provided. However, if you experience a technical issue that prevents you from using the service, please contact us within 7 days of purchase at contact@cognitivesquad.com.</p>

          <h2>4. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use AlgoBook for any unlawful purpose</li>
            <li>Attempt to gain unauthorized access to any part of the platform</li>
            <li>Submit malicious code that could harm our infrastructure</li>
            <li>Share your account credentials with others</li>
            <li>Scrape, crawl, or use automated tools to extract data from AlgoBook</li>
            <li>Reproduce, redistribute, or sell content generated by AlgoBook</li>
            <li>Use the platform to harass, abuse, or harm other users</li>
          </ul>

          <h2>5. Intellectual Property</h2>
          <h3>5.1 Our Content</h3>
          <p>The AlgoBook platform, including its design, features, and AI-generated questions, is the intellectual property of CognitiveSquad. You may not copy, modify, or distribute our platform content.</p>

          <h3>5.2 Your Content</h3>
          <p>You retain ownership of the code you write on AlgoBook. By using the platform, you grant us a limited license to store and process your submissions for the purpose of providing the service.</p>

          <h2>6. AI-Generated Content</h2>
          <p>Questions and hints are generated using AI (GPT-4). While we strive for accuracy, AI-generated content may occasionally contain errors. AlgoBook is a practice tool and should not be the sole basis for interview preparation decisions.</p>

          <h2>7. Code Execution</h2>
          <p>Code submitted through AlgoBook is executed in a sandboxed environment. We reserve the right to limit execution time, memory usage, and the number of executions to prevent abuse.</p>

          <h2>8. Termination</h2>
          <p>We reserve the right to suspend or terminate your account if you violate these Terms. You may delete your account at any time by contacting us at contact@cognitivesquad.com.</p>

          <h2>9. Limitation of Liability</h2>
          <p>AlgoBook is provided &quot;as is&quot; without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the platform. Our total liability shall not exceed the amount you paid for the service in the 12 months preceding the claim.</p>

          <h2>10. Changes to Terms</h2>
          <p>We may update these Terms from time to time. Continued use of AlgoBook after changes constitutes acceptance of the new Terms. We will make reasonable efforts to notify users of significant changes.</p>

          <h2>11. Governing Law</h2>
          <p>These Terms are governed by the laws of India. Any disputes shall be resolved in the courts of competent jurisdiction in India.</p>

          <h2>12. Contact Us</h2>
          <p>For questions about these Terms, please contact us at:</p>
          <p><strong>Email:</strong> contact@cognitivesquad.com</p>
        </div>
      </main>
    </div>
  );
}
